server:
  contextPath: /inditest/v1
  servlet.context-path: /inditest/v1
  port: 9654

spring:
  datasource:
    url: jdbc:h2:mem:inditest
    driver-class-name: org.h2.Driver
    username: 1234
    password: 1234
  h2:
    console:
      enabled: true